# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# solo ordering , Fabricorg with 3 template peers , 2 users , Sawtoothorg with 2 template 2 users

# HLStudyGroupdomain
# SawtoothSawtooth
#FabricFabric
version: '2'

volumes:
  orderer.HLStudyGroup.com:
  peer0.Sawtooth.HLStudyGroup.com:
  peer1.Sawtooth.HLStudyGroup.com:
  peer0.Fabric.HLStudyGroup.com:
  peer1.Fabric.HLStudyGroup.com:
  peer2.Fabric.HLStudyGroup.com:

networks:
  byfnSG :

services:

  orderer.HLStudyGroup.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.HLStudyGroup.com
    container_name: orderer.HLStudyGroup.com
    networks:
      - byfnSG 

  peer0.Sawtooth.HLStudyGroup.com:
    container_name: peer0.Sawtooth.HLStudyGroup.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Sawtooth.HLStudyGroup.com
    networks:
      - byfnSG 

  peer1.Sawtooth.HLStudyGroup.com:
    container_name: peer1.Sawtooth.HLStudyGroup.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.Sawtooth.HLStudyGroup.com
    networks:
      - byfnSG 

  peer0.Fabric.HLStudyGroup.com:
    container_name: peer0.Fabric.HLStudyGroup.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Fabric.HLStudyGroup.com
    networks:
      - byfnSG 

  peer1.Fabric.HLStudyGroup.com:
    container_name: peer1.Fabric.HLStudyGroup.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.Fabric.HLStudyGroup.com
    networks:
      - byfnSG 

  peer2.Fabric.HLStudyGroup.com:
    container_name: peer2.Fabric.HLStudyGroup.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.Fabric.HLStudyGroup.com
    networks:
      - byfnSG 

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.Sawtooth.HLStudyGroup.com:7051
      - CORE_PEER_LOCALMSPID=SawtoothMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Sawtooth.HLStudyGroup.com/peers/peer0.Sawtooth.HLStudyGroup.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Sawtooth.HLStudyGroup.com/peers/peer0.Sawtooth.HLStudyGroup.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Sawtooth.HLStudyGroup.com/peers/peer0.Sawtooth.HLStudyGroup.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Sawtooth.HLStudyGroup.com/users/Admin@Sawtooth.HLStudyGroup.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.HLStudyGroup.com
      - peer0.Sawtooth.HLStudyGroup.com
      - peer1.Sawtooth.HLStudyGroup.com
      - peer0.Fabric.HLStudyGroup.com
      - peer1.Fabric.HLStudyGroup.com
      - peer2.Fabric.HLStudyGroup.com
    networks:
      - byfnSG 
